basePath: /
definitions:
  models.RequestCifrarDTO:
    properties:
      chave:
        type: string
      textoClaro:
        type: string
    required:
    - chave
    - textoClaro
    type: object
  models.RequestDecifrarDTO:
    properties:
      chave:
        type: string
      textoCifrado:
        type: string
    type: object
  models.ResponseCifrarDTO:
    properties:
      textoCifrado:
        type: string
    type: object
  models.ResponseDecifrarDTO:
    properties:
      textoClaro:
        type: string
    required:
    - textoClaro
    type: object
host: localhost:8080
info:
  contact: {}
  description: API que implementa a cifra de Vernam (criptografia e descriptografia
    de mensagens).
  title: API Cifra de Vernam
  version: "1.0"
paths:
  /cifrar:
    post:
      consumes:
      - application/json
      description: Aplica a cifra de Vernam ao texto fornecido com a chave informada.
      parameters:
      - description: Texto e chave
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RequestCifrarDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseCifrarDTO'
      summary: Cifrar uma mensagem com uma chave
      tags:
      - criptografia
  /decifrar:
    post:
      consumes:
      - application/json
      description: Aplica a cifra de Vernam ao texto fornecido com a chave informada.
      parameters:
      - description: Texto e chave
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RequestDecifrarDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseDecifrarDTO'
      summary: Decifrar mensagem com cifra de vernan
      tags:
      - descriptografia
swagger: "2.0"
