basePath: /
definitions:
  models.CriptoDescriptoRequest:
    properties:
      chave:
        type: string
      texto:
        type: string
    required:
    - chave
    - texto
    type: object
  models.CriptoDescriptoResponse:
    properties:
      resultado:
        type: string
    type: object
  models.CriptografiaChaveAleatoriaRequest:
    properties:
      texto:
        type: string
    required:
    - texto
    type: object
  models.CriptografiaChaveAleatoriaResponse:
    properties:
      chave_usada:
        type: string
      texto_criptografado:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API que implementa a cifra de Vernam (criptografia e descriptografia
    de mensagens).
  title: API Cifra de Vernam
  version: "1.0"
paths:
  /criptografar-com-chave-aleatoria:
    post:
      consumes:
      - application/json
      description: Aplica a cifra de Vernam ao texto fornecido com chave aleatória.
      parameters:
      - description: Texto e chave
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CriptografiaChaveAleatoriaRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CriptografiaChaveAleatoriaResponse'
      summary: Criptografar com chave aleatória
      tags:
      - criptografia
  /criptografar-com-chave-propria:
    post:
      consumes:
      - application/json
      description: Aplica a cifra de Vernam ao texto fornecido com a chave informada.
      parameters:
      - description: Texto e chave
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CriptoDescriptoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CriptoDescriptoResponse'
      summary: Criptografar com sua chave
      tags:
      - criptografia
  /descriptografar:
    post:
      consumes:
      - application/json
      description: Aplica a cifra de Vernam ao texto fornecido com a chave informada.
      parameters:
      - description: Texto e chave
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CriptoDescriptoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CriptoDescriptoResponse'
      summary: Descriptografar mensagem com cifra de vernan
      tags:
      - descriptografia
swagger: "2.0"
